### PR TITLE
Revamped build and compressed screenshot v2

### PR DESCRIPTION
**Pull request by GabrielRavier**
I revamped the build (and it works).

To follow up on the things mentioned on pr https://github.com/cuckydev/Cave-Story-Engine-2/pull/56 : 

1. I fixed the data folder (it works)
2. I'd like to know whether I actually have to rename the game data folder (or if you just think it's a shit idea).
3. I made the build actually make dependencies
4. I'd like to know whether putting `rsync` as a new dependency is fine
5. I'd like to know if it's really a problem to have extra `echo`s in the build. I think they're better as they add extra feedback, but @Clownacy seems to thing they "make parallel builds confusing".

### CODE REVIEW

**Comment by GabrielRavier** [comment]
Also closing the pull request every time you find a problem with it isn't really how you're supposed to do this.  According to [GitHub's guidelines](https://github.blog/2016-03-15-kindly-closing-pull-requests/) , you should only close pull requests you will never accept, that you cannot accept, on unmaintained projects, or if they turn sour

**Comment by Clownacy** [comment]
I am so sick of your patronising. Once again you've made a broken pull request that you haven't properly tested. Instead of strawmanning me and acting like I don't know how to use this website, maybe stop and listen to yourself:

> you should only close pull requests you will never accept

Maybe then you'd figure out why I closed the last request. _Every_ one you make is riddled with bugs and unwelcome changes. And you wonder why your pull requests to the Sonic disassemblies never get merged?

**Comment by GabrielRavier** [comment]
I mean, I kinda thought the point of a pull request was to be able to have it [reviewed](https://help.github.com/articles/about-pull-request-reviews/), not to have someone tell me it's bad and close it.

**Comment by GabrielRavier** [comment]
I'd also like to know whether you're just considering that that last PR (and this one) was just something that'd never ever get accepted even if I fixed it and addressed all your complaints or if you just assumed I wouldn't fix it.

**Comment by GabrielRavier** [comment]
Also when you're talking about strawmanning, I don't really get what you mean (I know what strawmanning is, and I don't really see how I was misrepresenting anything)

**Comment by GabrielRavier** [comment]
Also if by "I am so sick of your patronising." you're referring to my habit of putting links everywhere, I just do that because I think it makes my posts more credible and less liable to people saying "wait wtf where did you get that from".

**Comment by GabrielRavier** [comment]
Also about "Once again you've made a broken pull request that you haven't properly tested" I'd like to know what you're referring to because I've just done a `make clean` `make -j 5 FIX_BUGS=1 STATIC=1 WINDOWS=1` for the fifth time now and I still don't see any issues.

**Pull request closed without merging**
